export const ADD_ITEM = 'ADD_ITEM';
export const LOAD_ITEMS = 'LOAD_ITEMS';
export const DELETE_ITEM = 'DELETE_ITEM';
export const TOGGLE_BUY_ITEM = 'TOGGLE_BUY_ITEM';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const TOGGLE_BUY_ITEM_SUCCESS = 'TOGGLE_BUY_ITEM_SUCCESS';